wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1670048273.35455
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      4: 3.8.5
      5: 0.13.5
      8:
      - 5
batch_size:
  desc: null
  value: 4
epochs:
  desc: null
  value: 40
learning_rate:
  desc: null
  value: 0.002
save_checkpoint:
  desc: null
  value: true
